apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-system-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payment-system.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/{{ .Values.postgres.db }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.user | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  GATEWAY_URL: "http://websocket-gateway:{{ .Values.websocketGateway.port }}"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
