apiVersion: v1
kind: Secret
metadata:
  name: payment-system-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payment-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  INTERNAL_API_KEY: {{ .Values.secrets.internalApiKey | quote }}
