server:
  port: 8083

spring:
  application:
    name: websocket-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}

security:
  internal-api-key: ${SECURITY_INTERNAL_API_KEY:dev-insecure-key-replace-in-prod}

logging:
  level:
    com.zez: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
